# This file may be used to create an environment using:
# $ conda create --name <env> --file <this file>
# platform: osx-64
ca-certificates
certifi
libblas
libcblas
libcxx
libffi
libgfortran
liblapack
libopenblas
llvm-openmp
ncurses
numpy
openssl
pip
python
python_abi
readline
setuptools
sqlite
tk
wheel
xz
zlib
